import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import BudgetPage from "./@expenses/page";
import TheBuget from "./@budget/page";
import RevenuePage from "./@revenue/page";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ComplexLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <BudgetPage />     <TheBuget />  <RevenuePage />           {children}
            </body>
        </html>
    );
}
